language: php
os: linux

php: 7.3

sudo: required

services:
  -docker

env:
  DOCKER_COMPOSE_VERSION: 1.23.2

before_install:
  # upgrade docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - ./dts init-conf

before_script:
  - mkdir -p build/logs
  - ./dts docker-compose up -d --build
  - ./dts composer install --no-interaction
  - sleep 10 # phinx will fail due to db not actually existing unless we wait...
  - ./dts exec phinx migrate

script:
  #- phpunit --coverage-clover build/logs/clover.xml
  - ./dts docker-compose exec dts phpunit --coverage-clover build/logs/clover.xml

after_script:
  - ./dts docker-compose down

after_success:
  # Submit coverage report to codecov.io
  - bash <(curl -s https://codecov.io/bash)

# cache composer for faster tests
cache:
  directories:
    - vendor
    - $HOME/.cache/composer